name: Build Loyalsoldier
on:
  push:
    branches: main
    paths:
      - '.github/workflows/build-packages-release.yml'
      - 'patch.sh'
      - 'do_not_build'
      - 'packages/Loyalsoldier-geodata/**'
      - '!packages/**/github/workflows/**'
      - '!packages/**/README*'
      - '!packages/**/.gitignore'
      - '!packages/**/LICENSE'
      - '!packages/**/LICENSES'

jobs:
  buildpkg:
    name: Build Openwrt Package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64-v23.05.0-rc3

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        uses: ekkog/gh-action-sdk@master
        env:
          ARCH: ${{ matrix.arch }}
          KEY_BUILD: ${{ secrets.KEY_BUILD }}
          INDEX: 1
          IGNORE_ERRORS: 1
          NO_SHFMT_CHECK: 1
          V: 99
          PACKAGES:
            Loyalsoldier-geodata


      - name: List files
        run: |
          ls -R bin/


      - name: Upload feed
        uses: Pendect/action-rsyncer@8e05ffa5c93e5d9c9b167796b26044d2c616b2b9
        with:
          flags: '-ahvHP'
          options: '--delete'
          src: 'bin/packages/*/action/'
          dest: '${{ secrets.SF_USER }}@frs.sourceforge.net:/home/frs/project/ekko-openwrt-dist/geodata/Loyalsoldier/'
        env:
          DEPLOY_KEY: ${{ secrets.SF_KEY }}